---
- name: Prepare prerequisites
  hosts: all
  become: true
  pre_tasks:
    - name: Ensure monitor group exists
      ansible.builtin.group:
        name: "{{ server_monitor_group }}"
        state: present
        system: true
    - name: Ensure monitor user exists
      ansible.builtin.user:
        name: "{{ server_monitor_user }}"
        group: "{{ server_monitor_group }}"
        system: true
        shell: /usr/sbin/nologin
        create_home: false
    - name: Ensure install dir exists
      ansible.builtin.file:
        path: "{{ server_monitor_install_dir }}"
        state: directory
        owner: "{{ server_monitor_user }}"
        group: "{{ server_monitor_group }}"
        mode: '0750'
    - name: Ensure secrets dir exists
      ansible.builtin.file:
        path: "{{ server_monitor_secrets_dir }}"
        state: directory
        owner: "{{ server_monitor_user }}"
        group: "{{ server_monitor_group }}"
        mode: '0700'
  roles:
    - role: monitoring
