---
- name: Restart managed Alertmanager service
  community.docker.docker_compose_v2:
    project_src: "{{ app_repo_target }}"
    state: restarted
    services:
      - alertmanager
    files: >-
      {{ ['compose.yaml']
         + (['compose.slack.yaml.example'] if app_use_slack_overlay else [])
         + ['compose.ansible.yaml']
         + app_compose_additional_files }}
  when:
    - not ansible_check_mode
    - app_compose_state == 'present'

- name: Restart managed Prometheus service
  community.docker.docker_compose_v2:
    project_src: "{{ app_repo_target }}"
    state: restarted
    services:
      - prometheus
    files: >-
      {{ ['compose.yaml']
         + (['compose.slack.yaml.example'] if app_use_slack_overlay else [])
         + ['compose.ansible.yaml']
         + app_compose_additional_files }}
  when:
    - not ansible_check_mode
    - app_compose_state == 'present'
